INSERT INTO HM.MVCHIBOARD (ID, NAME, TITLE, CONTENT, PASS) VALUES(seq_board_num.nextval, '홍길동ㅋ2', '2023년53', '2023년입니다.....', '1234');
INSERT INTO HM.MVCHIBOARD (ID, NAME, TITLE, CONTENT, PASS) VALUES(seq_board_num.nextval, '마블22', '2024년53', '2024년입니다.....', '1234');
INSERT INTO HM.MVCHIBOARD (ID, NAME, TITLE, CONTENT, PASS) VALUES(seq_board_num.nextval, '헐크22', '2025년53', '2025년입니다.....', '1234');
INSERT INTO HM.MVCHIBOARD (ID, NAME, TITLE, CONTENT, PASS) VALUES(seq_board_num.nextval, '홈즈22', '2026년53', '2026년입니다.....', '1234');
INSERT INTO HM.MVCHIBOARD (ID, NAME, TITLE, CONTENT, PASS) VALUES(seq_board_num.nextval, '명탐정22', '2027년53', '2027년입니다....', '1234');

INSERT INTO HM.MVCHIBOARD (ID, NAME, TITLE, CONTENT, POSTDATE, OFILE, SFILE, DOWUNCOUNT, PASS, VISITCOUNT) VALUES(0, '', '', '', sysdate , '', '', 0 , '', 0 );

UPDATE MVCHIBOARD  SET VISITCOUNT = VISITCOUNT + 1 WHERE id = '264';   -- 264(id) 카운트 1증가  

UPDATE MVCHIBOARD SET DOWUNCOUNT = DOWUNCOUNT  + 1 WHERE ID  = '266';  -- 다운카운트 증가

SELECT COUNT(*) FROM MVCBOARD WHERE pass = '1234' AND id = '266'; 

DELETE FROM MVCHIBOARD WHERE id = '270';
ROLLBACK;

UPDATE HM.MVCHIBOARD SET TITLE='잘가 아주 잘가', NAME='성계야성계',  CONTENT='왜 그렇게 있는거야 ', OFILE='', SFILE='' 
WHERE ID = '270' AND pass = '1234';
ROLLBACK;