-- CREATE TABLE (삭제시 PURGE 사용됨)
-- TB_DEPT_TEMP 테이블 생성
DROP TABLE HM.TB_DEPT_TEMP PURGE;
CREATE TABLE HM.TB_DEPT_TEMP
(
	DEPT_CD CHAR(6) NOT NULL
	, DEPT_NM VARCHAR2(150) NOT NULL
	, UPPER_DEPT_CD CHAR(6)
);

-- TB_DEPT_TEMP 테이블 기본 키 생성
ALTER TABLE HM.TB_DEPT_TEMP 
	ADD CONSTRAINT PK_TB_DEPT_TEMP PRIMARY KEY (DEPT_CD);

-- 
DROP TABLE HM.TB_EMP_TEMP PURGE;
CREATE TABLE HM.TB_EMP_TEMP
(
	EMP_NO CHAR(10) NOT NULL
	, EMP_NM VARCHAR2(150) NOT NULL
	, BIRTH_DE CHAR(8) NOT NULL
	, LUNAR_YN CHAR(1) NOT NULL	
	, SEX_CD CHAR(3) NOT NULL
	, ADDR VARCHAR2(1000) NOT NULL
	, TEL_NO VARCHAR2(150) NOT NULL
	, FINAL_EDU_SE_CD CHAR(3) NOT NULL
	, SAL_TRANS_BANK_CD CHAR(3) NOT NULL
	, SAL_TRANS_ACCNT_NO VARCHAR2(20) NOT NULL
	, DIRECT_MANAGER_EMP_NO CHAR(10) NOT NULL
	, DEPT_CD CHAR(6) NOT NULL
);

-- 기본키 생성 PRIMARY KEY
ALTER TABLE HM.TB_EMP_TEMP ADD CONSTRAINT PK_TB_EMP_TEMP PRIMARY KEY(EMP_NO);


-- TB_EMP_TEMP 테이블에 TB_DEPT_TEMP 테이블의 DEPT_CD 컬럼을 참조하는 FK 생성하기
ALTER TABLE HM.TB_EMP_TEMP ADD CONSTRAINT FK_TB_EMP_TEMP_01 FOREIGN KEY(DEPT_CD)
REFERENCES HM.TB_DEPT_TEMP(DEPT_CD);

-- ADD COLUMN
ALTER TABLE HM.TB_EMP_TEMP ADD (MARRIED_YN CHAR(1));

-- DROOP COLUMN
ALTER TABLE HM.TB_EMP_TEMP DROP COLUMN MARRIED_YN;

-- MODIFY COLUMN - 생성, 수정, 삭제 
ALTER TABLE HM.TB_EMP_TEMP ADD (MARRIED_YN CHAR(1));
ALTER TABLE HM.TB_EMP_TEMP MODIFY (MARRIED_YN CHAR(1) DEFAULT 'N' NOT NULL);
ALTER TABLE HM.TB_EMP_TEMP DROP COLUMN MARRIED_YN;

-- RENAME COLUMN (ORACLE DBMS에서만 지원하는 기능)
CREATE TABLE HM.TB_EMP_TEMP_2
AS SELECT * FROM HM.TB_EMP_TEMP;

ALTER TABLE HM.TB_EMP_TEMP_2 
RENAME COLUMN TEL_NO TO PHONE_NO;

ALTER TABLE HM.TB_EMP_TEMP_2 
RENAME COLUMN PHONE_NO TO TEL_NO;

-- DROP CONSTRAINT
ALTER TABLE HM.TB_EMP_TEMP DROP CONSTRAINT FK_TB_EMP_TEMP_01;

-- ADD CONSTRAINT
ALTER TABLE HM.TB_EMP_TEMP ADD CONSTRAINT FK_TB_EMP_TEMP_01 
FOREIGN KEY (DEPT_CD) REFERENCES HM.TB_DEPT_TEMP(DEPT_CD); 

-- RENAME TABLE
RENAME TB_EMP_TEMP_2 TO TB_EMP_TEMP_3;

-- TRUNCATE TABLE
TRUNCATE TABLE HM.TB_EMP_TEMP_3;
